<a href="https://colab.research.google.com/github/ShivajiMallela/Deep-learning-with-Tensorflow/blob/main/Fundamentals_of_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Getting Started with TensorFlow: A Guide to the Basics

## What is TensorFlow?

[TensorFlow](https://www.tensorflow.org/) is a comprehensive open-source library designed for machine learning. It helps with data preprocessing, model building, and deploying models so others can use them.

## Why Use TensorFlow?

Instead of creating machine learning and deep learning models from scratch, TensorFlow offers a robust library with many built-in functions that you'll likely need. This makes it easier and faster to develop models.

## What We'll Cover

TensorFlow has a broad range of capabilities, but the core idea is simple: convert data into numerical form (tensors) and use machine learning algorithms to discover patterns.

In this notebook, we will explore some fundamental operations in TensorFlow, including:
* Introduction to tensors (how to create them)
* Extracting information from tensors (tensor attributes)
* Manipulating tensors (tensor operations)
* Working with tensors and NumPy
* Using `@tf.function` to optimize your Python functions
* Utilizing GPUs with TensorFlow

### Key Points to Remember:
* Many processes will be handled automatically when you build a model, but understanding these fundamentals will help you recognize what's happening behind the scenes.
* Whenever you encounter a TensorFlow function, it's crucial to check the official documentation. You can access the [Python API docs](https://www.tensorflow.org/api_docs/python/) to find detailed information on any function you need. It may seem daunting initially, but with practice, navigating the documentation will become easier.


# Introduction to Tensors

In [1]:
# Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.15.0


In [2]:
# creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
scalar.ndim

0

- **Definition:** A scalar is a single number, a quantity that is fully described by a single value. It has no direction, only magnitude.

- **Rank**: The rank of a tensor indicates the number of dimensions or indices needed to describe it. Scalars are considered rank-0 tensors because they have no dimensions. They are just single values.

In [4]:
# create a vector more than 0 dimensions
vector = tf.constant([2,6])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 6], dtype=int32)>

In [5]:
vector.ndim

1

**Vector:** (Rank-1 Tensor) A vector has magnitude and direction and requires one index to describe it.

In [6]:
# create a matrix more than one dimension
matrix = tf.constant([[6,8],
                      [5,9]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[6, 8],
       [5, 9]], dtype=int32)>

In [7]:
matrix.ndim

2

**Matrix:** (Rank-2 Tensor) A matrix requires two indices to describe its components, representing a grid of numbers

In [8]:
# Lets create another matrix and define datatype
matrix2 = tf.constant([[2., 4.],
                      [6., 7.],
                      [3., 6.]], dtype=tf.float32)
matrix2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[2., 4.],
       [6., 7.],
       [3., 6.]], dtype=float32)>

In [9]:
matrix.ndim

2

In [10]:
# How about a tensor? (more than 2 dimensions, although, all of the above items are also technically tensors)
tensor = tf.constant([[[1,2,3],
                      [4,5,6]],
                      [[2,4,6],
                      [3,5,7]],
                      [[7,8,9],
                       [9,7,5]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[2, 4, 6],
        [3, 5, 7]],

       [[7, 8, 9],
        [9, 7, 5]]], dtype=int32)>

In [11]:
tensor.ndim

3

This is known as a rank 3 tensor (3-dimensions).
A tensor is a mathematical object that can have an arbitrary number of dimensions.

For example, you might turn a series of images into tensors with shape (224, 224, 3, 32), where:
* 224, 224 (the first 2 dimensions) are the height and width of the images in pixels.
* 3 is the number of color channels of the image (red, green, blue).
* 32 is the batch size (the number of images a neural network processes at any one time).

All of the above variables we've created are actually tensors. They can also be referred to by different names based on their dimensions:
* **Scalar**: A single number (0-dimensional tensor).
* **Vector**: A 1-dimensional array of numbers (e.g., wind speed with direction).
* **Matrix**: A 2-dimensional array of numbers.
* **Tensor**: An n-dimensional array of numbers, where n can be any number (0-dimensional is a scalar, 1-dimensional is a vector, 2-dimensional is a matrix, and so on).

### Creating Tensors with `tf.variable`

We can also create tensors using `tf.variable()`

* `tf.Variable()`: Creates a tensor whose value can be changed during training, suitable for model parameters like weights.
* `tf.constant()`: Creates an immutable tensor whose value cannot be altered after creation, useful for fixed data

In [12]:
# Create the same tensor with tf.Variable() and tf.constant()
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

Now let's try to change one of the elements of the changable tensor.


In [13]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [14]:
# Will display error because it is immutable
# unchangeable_tensor[0].assign(7)
# unchangeable_tensor

Which one should you use? `tf.constant()` or `tf.Variable()`?

It will depend on what your problem requires. However, most of the time, TensorFlow will automatically choose for you (when loading data or modelling data).

## Create Random tensors

**Creating Random Tensors:**
Random tensors are tensors of arbitrary size that contain random numbers. They are essential in various machine learning tasks, particularly in initializing neural networks.

**Why Create Random Tensors?**

Neural networks use random tensors to initialize their weights (patterns) that they aim to learn from the data. During the learning process, the network takes these random n-dimensional arrays of numbers and refines them through training until they represent some kind of pattern. This pattern is a compressed way to represent the original data.

we can create random tensors by using `tensor.random.generator` class

In [15]:
# create two random tensors (which are same)
random_1 = tf.random.Generator.from_seed(66)
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(66)
random_2 = random_2.normal(shape=(3,2))

# checking if they are equal
random_1, random_2, random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.5517507 , -0.3741098 ],
        [-0.28709963,  1.5089895 ],
        [-0.14833727, -1.2846564 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.5517507 , -0.3741098 ],
        [-0.28709963,  1.5089895 ],
        [-0.14833727, -1.2846564 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [16]:
# We can also create random tensor directly
random_2 = tf.random.normal(shape=(3,2), seed=66)
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-1.3124319 , -1.4189664 ],
       [ 0.6897811 ,  0.3063817 ],
       [ 0.88849425,  0.23323588]], dtype=float32)>

- **Using `tf.random.Generator.from_seed`:**

tf.random.Generator.from_seed(seed) creates a new TensorFlow random number generator with the specified seed.
This generator can then be used to produce random numbers with methods like .normal(shape)

- **Using `tf.random.normal(seed=seed_value)`:**

tf.random.normal(shape, seed=seed_value) directly generates a tensor of random numbers with the specified shape and see

## Shuffle the order of elements in a tensor

In [17]:
# Shuffle a tensor
not_shuffled = tf.constant([[10,7],
                           [6,8],
                           [1,6]])

#shuffle our non_shuffled tensor
shuffled = tf.random.shuffle(not_shuffled)

In [18]:
not_shuffled, shuffled

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 6,  8],
        [ 1,  6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 1,  6],
        [10,  7],
        [ 6,  8]], dtype=int32)>)

In [19]:
tf.random.set_seed(42) # Global level random seed
tf.random.shuffle(not_shuffled, seed=42) # Operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 6,  8],
       [ 1,  6]], dtype=int32)>

In [20]:
# create a tensor of all ones and zeros
ones = tf.ones(shape=(3,4))
zeros = tf.zeros(shape=(3,4))

In [21]:
ones, zeros

(<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=float32)>)

You can also turn NumPy arrays in into tensors.

Remember, the main difference between tensors and NumPy arrays is that tensors can be run on GPUs.

> 🔑 **Note:** A matrix or tensor is typically represented by a capital letter (e.g. `X` or `A`) where as a vector is typically represented by a lowercase letter (e.g. `y` or `b`).

In [22]:
# Turn numpy arrays into tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [23]:
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [24]:
B = tf.constant(numpy_A, shape=(6,4))
B

<tf.Tensor: shape=(6, 4), dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]], dtype=int32)>

In [25]:
C = tf.constant(numpy_A, shape=(3,2,4))
C

<tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [26]:
print(A.ndim)
print(B.ndim)
print(C.ndim)

1
2
3


# Getting information from the tensors

When working with tensors, it's important to understand and be able to retrieve various pieces of information from them. Here are some key terms you should know:

**Shape:** The length (number of elements) of each dimension of a tensor.

**Rank:** The number of dimensions a tensor has. For example, a scalar has rank 0, a vector has rank 1, a matrix has rank 2, and a higher-dimensional tensor has rank n.

**Axis or Dimension:** Refers to a specific dimension of a tensor.

**Size:** The total number of elements in the tensor.
Understanding these terms is crucial, especially when aligning the shapes of your data with the shapes required by your model. For instance, ensuring that the shape of your image tensors matches the input layer of your model is essential.

We've previously used the ndim attribute to determine the number of dimensions (rank) of a tensor. Now, let's explore how to obtain other pieces of information such as shape and size.

In [27]:
# creating  a rank 4 tensor (4 dimensions)

rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [28]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [29]:
# Get various attributes of our tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 5
Total number of elements (2*3*4*5): 120


## indexing tensors

You can also index tensors just like python lists

In [30]:
# Get the first 2 items of each distribution
rank_4_tensor [:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [31]:
# Get the dimension from each index except for the final index
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [32]:
# create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[1,3],
                             [5,6]])
# Get the last element of each row
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 6], dtype=int32)>

We can also add dimensions to your tensor whilst keeping the same information present using `tf.newaxis`.

In [33]:
# Add an extra dimension (to the end)
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_2_tensor, rank_3_tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 3],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[1],
         [3]],
 
        [[5],
         [6]]], dtype=int32)>)

We can do the same with `tf.expand_dims()`.

In [34]:
tf.expand_dims(rank_2_tensor, axis=-1) # last axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [3]],

       [[5],
        [6]]], dtype=int32)>

In [35]:
tf.expand_dims(rank_2_tensor, axis=0) # first axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[1, 3],
        [5, 6]]], dtype=int32)>

In [36]:
tf.expand_dims(rank_2_tensor, axis=1) # second axis

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[1, 3]],

       [[5, 6]]], dtype=int32)>

# Tensor operations

**Basic operations**

Some of the basic operations are `+`, `-`, `*`.

In [37]:
# Add values to the tensor using `+` operation
tensor = tf.constant([[10,7],
                      [6,8]])
tensor_add = tensor + 10
tensor_add

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [16, 18]], dtype=int32)>

In [38]:
# subtraction and multiplication
tensor_sub = tensor-10
tensor_mul = tensor*10

tensor_sub, tensor_mul

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 0, -3],
        [-4, -2]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[100,  70],
        [ 60,  80]], dtype=int32)>)

In [39]:
tensor + 10, tensor-10, tensor*10

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[20, 17],
        [16, 18]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 0, -3],
        [-4, -2]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[100,  70],
        [ 60,  80]], dtype=int32)>)

Since we've used `tf.constant`, the original tensor is unchanged (The operations gets done on a copy of original tensor)

In [40]:
# original tensor
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 6,  8]], dtype=int32)>

We can also use the tensorflow inbuilt functions to do such operations

In [41]:
tf.add(tensor, 10) # addition

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [16, 18]], dtype=int32)>

In [42]:
tf.subtract(tensor, 10) # subtraction

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-4, -2]], dtype=int32)>

In [43]:
tf.multiply(tensor, 10) # multiply

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 60,  80]], dtype=int32)>

## Matrix multiplication

One of the most common operations in machine learning algorithms is [Matrix multiplication](https://www.mathsisfun.com/algebra/matrix-multiplying.html).

TensorFlow provides matrix multiplication functionality through the `tf.matmul()` method.

Here are the two key rules to remember for matrix multiplication:

The inner dimensions must match:

* `(3, 5) @ (3, 5)` won't work
* `(5, 3) @ (3, 5)` will work
* `(3, 5) @ (5, 3)` will work

The resulting matrix has the shape of the outer dimensions:
* `(5, 3) @ (3, 5)` results in a `(5, 5)` matrix
* `(3, 5) @ (5, 3)` results in a `(3, 3)` matrix

🔑**Note:** In Python, '`@`' is the operator for matrix multiplication.

In [44]:
# Matrix multiplication in TensorFlow
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 6  8]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[142, 126],
       [108, 106]], dtype=int32)>

In [45]:
# Matrix multiplication with Python operator '@'
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[142, 126],
       [108, 106]], dtype=int32)>

Both of these examples work because our `tensor` variable is of shape (2, 2).

What if we created some tensors which had mismatched shapes?

In [46]:
# Create (3, 2) tensor
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [47]:
# Try to matrix multiply them
# X @ Y

#(will show error)

Trying to matrix multiply two tensors with the shape `(3, 2)` errors because the inner dimensions don't match.

We need to either:
* Reshape X to `(2, 3)` so it's `(2, 3) @ (3, 2)`.
* Reshape Y to `(3, 2)` so it's `(3, 2) @ (2, 3)`.

We can do this with either:
* [`tf.reshape()`](https://www.tensorflow.org/api_docs/python/tf/reshape) - allows us to reshape a tensor into a defined shape.
* [`tf.transpose()`](https://www.tensorflow.org/api_docs/python/tf/transpose) - switches the dimensions of a given tensor.

Let's try `tf.reshape()` first.

In [48]:
# Example of reshape (3, 2) -> (2, 3)
tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [49]:
# Try matrix multiplication with reshaped Y
X @ tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

It worked, let's try the same with a reshaped `X`, except this time we'll use [`tf.transpose()`](https://www.tensorflow.org/api_docs/python/tf/transpose) and `tf.matmul()`.

In [50]:
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

In [51]:
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [52]:
# You can achieve the same result with parameters
tf.matmul(a=X, b=Y, transpose_a=True, transpose_b=False)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

## The dot product

Multiplying matrices by eachother is also referred to as the dot product.

You can perform the `tf.matmul()` operation using [`tf.tensordot()`](https://www.tensorflow.org/api_docs/python/tf/tensordot).

In [53]:
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [54]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [55]:
tf.matmul(X, tf.reshape(Y, (2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

We got the results differently because performing `tf.reshape()` and `tf.transpose()` dosen't give same values

In [56]:
# Check values of Y, reshape Y and tranposed Y
print("Normal Y:")
print(Y, "\n") # "\n" for newline

print("Y reshaped to (2, 3):")
print(tf.reshape(Y, (2, 3)), "\n")

print("Y transposed:")
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2, 3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


* `tf.reshape()` - changes the shape of the given tensor (first) and then insert values in order they appear (in our case, 7, 8, 9, 10, 11, 12).
* `tf.transpose()`- swaps the order of the axes, by default the last axis becomes the first, however the order can be changed using the [`perm` parameter](https://www.tensorflow.org/api_docs/python/tf/transpose).

## Changing the datatype of a tensor

Changing the dtype (data type) in TensorFlow is important for several reasons:

**Precision and Accuracy:**

Different tasks require different levels of precision. For instance, using tf.float32 (32-bit floating-point) may be sufficient for many machine learning tasks, but for tasks requiring higher precision, tf.float64 (64-bit floating-point) might be needed.

**Performance:**

Operations on smaller data types (e.g., tf.float16 or tf.int8) are generally faster and consume less memory compared to larger data types (e.g., tf.float64). Using the appropriate data type can significantly speed up computations and reduce resource usage.

In [57]:
# Create a new tensor with default datatype (float32)
B = tf.constant([1.7, 7.4])

# Create a new tensor with default datatype (int32)
C = tf.constant([1, 7])
B, C

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 7], dtype=int32)>)

In [58]:
# Change from float32 to float16 (reduced precision)
B = tf.cast(B, dtype=tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [59]:
# Change from int32 to float32
C = tf.cast(C, dtype=tf.float32)
C

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 7.], dtype=float32)>

## Get the absolute value

Sometimes you'll want the absolute values (all values are positive) of elements in your tensors.

To do so, you can use [`tf.abs()`](https://www.tensorflow.org/api_docs/python/tf/math/abs).

In [60]:
# Create tensor with negative values
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [61]:
# Get the absolute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

## Aggregating Tensors: Min, Max, Mean, Sum
You can easily perform calculations on an entire tensor to find values like the minimum, maximum, mean, and sum.

Here are the main functions you can use:

* `tf.reduce_min()` - finds the minimum value in a tensor.
* `tf.reduce_max()` - finds the maximum value in a tensor.
* `tf.reduce_mean()` - calculates the mean of all elements in a tensor.
* `tf.reduce_sum()` - calculates the sum of all elements in a tensor.

**Note:** These functions are usually found under the math module (e.g., tf.math.reduce_min()), but you can also use their shorter aliases (e.g., tf.reduce_min())

In [62]:
# Create a tensor with random integer values between 20 and 60
E = tf.constant(np.random.randint(low=0, high=60, size=40))
E

<tf.Tensor: shape=(40,), dtype=int64, numpy=
array([52, 18, 20, 58, 58, 31, 31, 32, 14, 28,  3, 28, 15, 56, 17, 51, 36,
       46, 52, 52, 45, 17, 44, 24, 13, 41, 43, 21, 41, 36,  9,  2, 31, 15,
        1, 19, 15, 42, 45, 24])>

In [63]:
# Minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [64]:
# Maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=58>

In [65]:
# Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=30>

In [66]:
# Find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1226>

To find the standard deviation and variance we can use `tf.math.reduce_std()` and `tf.math.reduce_variance()` of elements in a tensor and datatypes of tensor should be real or complex.

In [67]:
tf.math.reduce_variance(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=263.3775>

In [68]:
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=16.22891>

TensorFlow Probability (TFP) extends TensorFlow with a range of statistical tools and functions, including additional aggregation methods.
Here are some key aggregation functions provided by TFP :
* `tfp.stats.variance()` - Computes the variance.
* `tfp.stats.stddev()` - Computes the standard deviation.
* `tfp.stats.covariance()` - Computes the covariance matrix.
* `tfp.stats.correlation()` - Computes the correlation matrix.
* `tfp.stats.percentile()` - Computes the specified percentile.
* `tfp.stats.quantiles()` - Computes the specified quantiles.

## Finding the positional maximum and minimum

Need to find where the maximum value occurs in a tensor? This can be useful for aligning your labels (e.g., `['Green', 'Blue', 'Red']`) with your prediction probabilities (e.g., `[0.98, 0.01, 0.01]`). Here, the predicted label (the one with the highest probability) would be 'Green'.

To find the position of the maximum or minimum value in a tensor, you can use:

* `tf.argmax()` - finds the position of the maximum element in a tensor.
* `tf.argmin()` - finds the position of the minimum element in a tensor.

In [69]:
# Create a tensor with 50 values between 0 and 1
F = tf.constant(np.random.random(50))
F

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([0.30671485, 0.74741836, 0.98838726, 0.63917007, 0.99462409,
       0.28703439, 0.50037912, 0.71883128, 0.11624428, 0.12593389,
       0.38948537, 0.66485193, 0.58845573, 0.17767664, 0.38959714,
       0.72220503, 0.9648597 , 0.18767921, 0.94170814, 0.64508513,
       0.42716478, 0.71366044, 0.19019612, 0.6732344 , 0.68365988,
       0.80048444, 0.84387532, 0.29376916, 0.29564016, 0.80779941,
       0.46177103, 0.92670063, 0.88551499, 0.85945562, 0.82320118,
       0.31091093, 0.70245058, 0.48189852, 0.57917923, 0.94101045,
       0.75750437, 0.27701965, 0.39307223, 0.62327134, 0.44373561,
       0.41444956, 0.32749589, 0.02472657, 0.56890665, 0.96322902])>

In [70]:
tf.argmax(F) #Maximum element position of F

<tf.Tensor: shape=(), dtype=int64, numpy=4>

In [71]:
tf.argmin(F) #Minimum element position of F

<tf.Tensor: shape=(), dtype=int64, numpy=47>

In [72]:
# Find the maximum element position of F
print(f"The maximum value of F is at position: {tf.argmax(F).numpy()}")
print(f"The maximum value of F is: {tf.reduce_max(F).numpy()}")
print(f"Using tf.argmax() to index F, the maximum value of F is: {F[tf.argmax(F)].numpy()}")
print(f"Are the two max values the same (they should be)? {F[tf.argmax(F)].numpy() == tf.reduce_max(F).numpy()}")

The maximum value of F is at position: 4
The maximum value of F is: 0.9946240857407691
Using tf.argmax() to index F, the maximum value of F is: 0.9946240857407691
Are the two max values the same (they should be)? True


## Squeezing tensor (Removes all the single dimensions)

In [73]:
# Create a tensor to get started
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [74]:
G.shape, G.ndim

(TensorShape([1, 1, 1, 1, 50]), 5)

In [75]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

## One-hot encoding

If you have a tensor of indicies and would like to one-hot encode it, you can use [`tf.one_hot()`](https://www.tensorflow.org/api_docs/python/tf/one_hot).

You should also specify the `depth` parameter (the level which you want to one-hot encode to).

In [76]:
# Create a list of indices
some_list = [0, 1, 2, 3, 4, 5, 6]

# One hot encode them
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(7, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

You can also specify values for `on_value` and `off_value` instead of the default `0` and `1`.

In [77]:
# Specify custom values for on and off encoding
tf.one_hot(some_list, depth=4, on_value="online", off_value="Offline")

<tf.Tensor: shape=(7, 4), dtype=string, numpy=
array([[b'online', b'Offline', b'Offline', b'Offline'],
       [b'Offline', b'online', b'Offline', b'Offline'],
       [b'Offline', b'Offline', b'online', b'Offline'],
       [b'Offline', b'Offline', b'Offline', b'online'],
       [b'Offline', b'Offline', b'Offline', b'Offline'],
       [b'Offline', b'Offline', b'Offline', b'Offline'],
       [b'Offline', b'Offline', b'Offline', b'Offline']], dtype=object)>

## Squaring, log, square root

In [78]:
# Create a new tensor
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [79]:
# Square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [80]:
# find the square root
tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [81]:
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

## Manipulating `tf.Variable` tensors

Tensors created with `tf.Variable()` can be changed in place using methods such as:

* [`.assign()`](https://www.tensorflow.org/api_docs/python/tf/Variable#assign) - assign a different value to a particular index of a variable tensor.
* [`.add_assign()`](https://www.tensorflow.org/api_docs/python/tf/Variable#assign_add) - add to an existing value and reassign it at a particular index of a variable tensor.

In [82]:
# Create a variable tensor
I = tf.Variable(np.arange(0, 5))
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([0, 1, 2, 3, 4])>

In [83]:
# Assign the final value a new value of 50
I.assign([0, 1, 2, 3, 50])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([ 0,  1,  2,  3, 50])>

In [84]:
# The change happens in place (the last value is now 50, not 4)
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([ 0,  1,  2,  3, 50])>

In [85]:
# Add 10 to every element in I
I.assign_add([10, 10, 10, 10, 10])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([10, 11, 12, 13, 60])>

In [86]:
# Again, the change happens in place
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([10, 11, 12, 13, 60])>

# Tensors and NumPy

We've seen some examples of tensors interact with NumPy arrays, such as, using NumPy arrays to create tensors.

Tensors can also be converted to NumPy arrays using:

* `np.array()` - pass a tensor to convert to an ndarray (NumPy's main datatype).
* `tensor.numpy()` - call on a tensor to convert to an ndarray.

Doing this is helpful as it makes tensors iterable as well as allows us to use any of NumPy's methods on them.

In [87]:
# Create a tensor from numpy array
arr = np.array([3., 7., 6.])
J = tf.constant(arr)
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([3., 7., 6.])>

In [88]:
# Convert tensor J to NumPy with np.array()
np.array(J), type(np.array(J))

(array([3., 7., 6.]), numpy.ndarray)

In [89]:
J.numpy(), type(J.numpy())

(array([3., 7., 6.]), numpy.ndarray)

By default tensors have `dtype=float32`, where as NumPy arrays have `dtype=float64`.

This is because neural networks (which are usually built with TensorFlow) can generally work very well with less precision (32-bit rather than 64-bit).

In [90]:
# Create a tensor from NumPy and from an array
numpy_J = tf.constant(np.array([3., 7., 10.])) # will be float64 (due to NumPy)
tensor_J = tf.constant([3., 7., 10.]) # will be float32 (due to being TensorFlow default)
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

# Using `@tf.function`

In your TensorFlow adventures, you might come across Python functions which have the decorator [`@tf.function`](https://www.tensorflow.org/api_docs/python/tf/function).

If you aren't sure what Python decorators do, [read RealPython's guide on them](https://realpython.com/primer-on-python-decorators/).

But in short, decorators modify a function in one way or another.

In the `@tf.function` decorator case, it turns a Python function into a callable TensorFlow graph. Which is a fancy way of saying, if you've written your own Python function, and you decorate it with `@tf.function`, when you export your code (to potentially run on another device), TensorFlow will attempt to convert it into a fast(er) version of itself (by making it part of a computation graph).

For more on this, read the [Better performnace with tf.function](https://www.tensorflow.org/guide/function) guide.

In [91]:
# Create a simple function
def function(x, y):
  return x ** 2 + y

x = tf.constant(np.arange(0, 10))
y = tf.constant(np.arange(50, 60))
function(x, y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 50,  52,  56,  62,  70,  80,  92, 106, 122, 140])>

In [92]:
# Create the same function and decorate it with tf.function
@tf.function
def tf_function(x, y):
  return x ** 2 + y

tf_function(x, y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 50,  52,  56,  62,  70,  80,  92, 106, 122, 140])>

If you noticed no difference between the above two functions (the decorated one and the non-decorated one) you'd be right.

Much of the difference happens behind the scenes. One of the main ones being potential code speed-ups where possible.

# Finding access to GPUs

Using a GPU in Google Colab can significantly speed up the processing of tasks that require heavy computational power.

we can check if can access to a GPU using [`tf.config.list_physical_devices()`](https://www.tensorflow.org/guide/gpu).

In [93]:
import tensorflow as tf
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

If you've got access to a GPU, the cell above should output something like:

`[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]`

You can also find information about your GPU using `!nvidia-smi`.

In [94]:
!nvidia-smi

Tue Jun 18 00:53:08 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   68C    P0              33W /  70W |    107MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

If we are connected to the GPU tensorflow automatically uses it, we don't need to do any process regarding that.